### ISSUE TITLE
Support for lowercase "expenses", "assets".

### ISSUE THREAD

**Issue by dan335** [ananthakumaran/paisa#140]
I figured out why the yearly Sankey graph wasn't working for me.  I has "expenses" and "assets" instead of "Expenses" and "Assets".

I posted previously in discussions.  https://github.com/ananthakumaran/paisa/discussions/21  After downloading the new version it still wasn't working.  Guessed that maybe it was because of capitalization and was right.  Works for me now.

Pretty sure ledger supports all lowercase for assets, expense etc.  Not positive though.

**Comment by ananthakumaran** [comment]
Well, the ledger doesn't care much about the account name. Paisa on the other hand needs to follow a strict naming convention, otherwise, it's not possible to figure out whether you are spending or investing money. As of today, you need to follow the naming convention documented here https://paisa.fyi/reference/accounts/ (case sensitive). There have been a few requests to make this configurable, I am figuring out how to do that. It would take some time.

**Comment by dan335** [comment]
Seems like ideally "expenses" or "Expenses" would work instead of being configurable.  Thanks, I'll follow those conventions.
