### ISSUE TITLE
error messages sometimes list of integers

### ISSUE THREAD

**Issue by samuelengineer** [ananthakumaran/paisa#143]
**Describe your Environment**
OS: Ubuntu 23.04
Paisa Version: 0.6.2
App Variant: CLI

**Describe the bug**

With my hledger ledger, paisa fails to sync the journal.  It outputs an error message at some assertion transactions (which could be the subject of another bug report, but I'm more interested in the error message right now.  The error message is output as a list of integers, instead of a message.  For example:

```
$ paisa update
INFO    Using config file: /home/ubuntu/...
INFO    Syncing transactions from journal
ERROR   {[104 108 101 100 103 101 114 58 32 69 114 114 111 114 58 32 47 104 111 109 101 47 117 98 117 110 116 117 ...] 0 0}
```
Converting the numbers to ascii reveals the error message. (example clipped for privacy)

I cannot reproduce with a more minimal example - eg. if I add a failing assertion to the default main.ledger created from paisa init.  In these cases, it successfully prints the hledger error output as expected.

**To Reproduce**

This seems specific to my ledger, which I'm not willing to share due to privacy concerns sorry.

**Expected behavior**

The error message from hledger displayed in a readable manner.

**Comment by ananthakumaran** [comment]
could you run `$ PAISA_DEBUG=true paisa update` and share the error log, this will include the filename, line number, and function name in the log which will help me figure out where the error log comes from.

**Comment by ananthakumaran** [comment]
does it work if you include `--ignore-assertions` flag to the hledger call? There are two independent issues here
1) The error should show the error message instead of list of numbers, I will debug this
2) I am not sure about the assertion failure, but I am ok to relax this for forecast transactions. Paisa will export all the future transactions using the `--forecast` flag. Since I am only interested in the forecast transactions, I can ignore assertion failure. If possible, try to check with hledger folks, because I don't know if it's supposed to use forecasted transactions for assertion.

**Comment by ananthakumaran** [comment]
The fix for both issues is available on master. Thanks for the confirming with Hledger team.
